# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^deploy/helm/.*/templates/
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: debug-statements
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks

  - repo: https://github.com/pycqa/isort
    rev: main
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black
