[build-system]
requires = ["setuptools >=57", "wheel", "setuptools_scm[toml] >=7.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.cruft]
skip = ["setup.cfg"]

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ["py310"]
